services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    ports:
      - "${MSSQL_PORT:-1433}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
      - ./data:/data
      - mssql_data:/var/opt/mssql
    restart: always

  db-viewer:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - ./cloudbeaver_data:/opt/cloudbeaver/workspace
    restart: always

volumes:
  mssql_data:
  cloudbeaver_data:
